apiVersion: v1
kind: Service
metadata:
  name: dvga-service-nodeport
  #name: nginx-service-nodeport
spec:
  type: NodePort
  selector:
    app: dvga
    #app: nginx
  ports:
    - #protocol: TCP
      port: 5013
      targetPort: 5013
      nodePort: 30011
