---
- name: Check if app is accessible through BIG-IP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - tmos_vars.yml

  tasks:
    - name: Wait for 30 seconds to ensure settings are applied
      pause:
        seconds: 30

    - name: Check if the server is available
      uri:
        url: "http://{{ item.ip }}:{{ virtual_server_port }}/endpoint1"
        method: GET
        status_code: 200
      register: result
      with_items: "{{ virtual_server }}"
